### PR TITLE
Fixes #181. Add comment folding as decribed in: https://lobste.rs/s/m5dl...

### LINKED ISSUE #181: Option to show top-level comments only
[This thread](https://lobste.rs/s/5ovrc2/what_s_your_most_controversial_technical_opinion) makes me really wish for the ability to only show top-level comments, or at least distinguish top-level comments somehow so yo can quickly identify them while scanning down the list of comments. I'm usually more interested in the top-level comments than the discussions hanging off from each of them.

### PR DESCRIPTION
**Pull request by BennyHallett**
Added comment folding feature as decribed in https://lobste.rs/s/m5dlun/comment_folding

### CODE REVIEW

**Comment by BennyHallett** [comment]
The JS isn't firing if you're not logged in, sorry. I'll fix that up and commit a fix asap.

**Comment by daGrevis** [comment]
(y)

**Comment by jcs** [comment]
There is no JS for logged out users, so the fold link should probably just not be there if there is no user.

Though if #189 were implemented, I wonder how useful folding would even be.  There are rarely huge threads that are hard to scroll through like on Reddit, but with vertical thread lines, it would make it much easier to see which comments are replying to which in a heavily nested comment thread.

**Comment by BennyHallett** [comment]
Thanks @jcs , I've stopped displaying the fold link when there is no user.

I see your point about the thread lines and having smaller threads. I still think folding is useful though, even with comment counts as low as 20 or so as in this thread: https://lobste.rs/s/kgdrdj/my_switch_to_openbsd_first_impressions

I like the ability to close off threads as I read them, or choose to ignore them based on the root comment.

**Comment by BennyHallett** [comment]
@jsc is there anything you need me to do to have this PR merged in?

**Pull request merged**
