### PR TITLE
I18n for settings

### PR DESCRIPTION
**Pull request by chaica**
Internationalization of the settings view and invitation form (used by the settings view)
- config/locales/en.yml : localize settings (controller, view) and invitation form
- config/locales/fr.yml : localize settings (controller, view), invitation form and activerecord error message about passwords not matching
- app/controllers/settings_controller.rb : i18n of settings controller
- app/views/settings/index.html.erb : i18n of settings view
- app/views/users/_invitationform.html.erb : i18n of invitation form view (used by settings view)

### CODE REVIEW

**Comment by chaica** [comment]
Hi,

Any news about this PR :) ?

Bye,
Carl

**Comment by chaica** [comment]
Hi,

Any news about this PR :) ?

Bye,
Carl

**Comment by chaica** [comment]
Hi,

Any news about this PR :) ?

Bye,
Carl

**Comment by chaica** [comment]
Hi,

Any update about this PR ?

Bye,
Carl

**Comment by chaica** [comment]
Hi,

Any update about this PR?

Bye,
Carl

**Comment by finkiki** [comment]
@jcs ?

**Comment by chaica** [comment]
any blocker on this PR? Can I help?

**Comment by 1gor** [comment]
@jcs , is there anything we can help with to get this PR accepted?

**Comment by HLFH** [comment]
cc @mrb @jcs Please merge.

**Comment by jcs** [comment]
Sorry, but I will not be merging any more localization (see 08daf1af0a773f9f3e3520cda27951e499ba659f).

**Comment by chaica** [comment]
For people being interested in an internationalized version of the lobste.rs engine, the work is fully completed and available at [the journalduhacker repository](https://gitlab.com/journalduhacker/journalduhacker) and in production on the french-speaking website [Le Journal du hacker](https://www.journalduhacker.net).

Sorry for the noise, but it is related to the initial topic.

**Comment by jcs** [comment]
@chaica You can't just remove my copyright from all of the code in your fork:

https://gitlab.com/journalduhacker/journalduhacker/commit/1e2c95e698986cede31a59d0d25b9ae0524262b7

While you are free to license your new code under your own license (AGPLv2 in your case), you have removed all of the licensing terms that must be applied to all of the files that were already there (authored by me).  In addition, you can only assert copyright (and change licensing terms) to new code that you have authored, or made significant changes to (for some legal definition of significant).

**Comment by HLFH** [comment]
@jcs Why should we care about your license if you don't care about merging a simple Pull Request?

**Comment by chaica** [comment]
Hi @jcs 
I just modified Readme.md to specify the different authors and licenses, added the license of the original project and the new license in the new license directory.

**Comment by qbit** [comment]
@HLFH because laws.

**Pull request closed without merging**
