### PR TITLE
Hide comments from specific users [issue #197]

### PR DESCRIPTION
**Pull request by andela-cdaniel**
This PR implements the feature requested in #197

### CODE REVIEW

**Comment by crertel** [comment]
Some questions:

* Why did you add a dependency on `capybara` when that wasn't there before, when the current tests seem to not use it?
* Why did you add a dependency on `pg` that wasn't there before, and why is the PG extension now a hard requirement, when the current codebase uses MySQL?
* Why did you add a dependency on `addressable` that wasn't there before?
* Why did you remove the limits on the text columns (and what does this mean for people submitting maliciously large data)?
* Why did you increase the limit on the vote column in the vote table?

Good testing though! Just maybe try to stick with the idioms already present in the codebase.

**Comment by andela-cdaniel** [comment]
> Why did you add a dependency on pg that wasn't there before, and why is the PG extension now a hard requirement, when the current codebase uses MySQL?

An oversight on my part (I'm most familiar with postgres and I used it instead of mysql).  I'll update the pr and remove the dependency on the postgres gem

> Why did you add a dependency on addressable that wasn't there before?

It's a runtime dependency for `Capybara` (added by the capybara gem)

> Why did you remove the limits on the text columns (and what does this mean for people submitting maliciously large data)?
> Why did you increase the limit on the vote column in the vote table?

This I got to look into as I only added the migration to create one new table (blocked users) and I am unclear as to why this would cause the limit constraints to be removed.

**Comment by crertel** [comment]
Thank you for answering my questions. :)

**Comment by pushcx** [comment]
> Why did you increase the limit on the vote column in the vote table?

Rails creates `schema.rb` by introspecting on the database. If PostgresSQL and MySQL differ in their understanding of a migration or implementation of a table, you'll get churn in the file.

The best way to avoid it is to `git add -p` after running a migration. To fix it, rollback the migration, `git add db/schema.rb`, re-run the migration, then `git add -p` only the deliberate changes (which may require manual editing). Then commit and `git checkout db/schema.rb` to toss the spurious changes.

**Comment by andela-cdaniel** [comment]
@crertel, @pushcx, I've updated the PR (removed the `pg` gem and retain the limits enforced on particular columns)

**Comment by danielcompton** [comment]
After squashing these commits, the rebase was trivial. What's needed next to move this PR forward?

**Comment by jcs** [comment]
I would like some community discussion on Lobsters on whether this type of feature is wanted.

**Comment by danielcompton** [comment]
I've made a meta post about this here: https://lobste.rs/s/debnsq/hiding_comments_by_specific_users

**Comment by jcs** [comment]
Sorry, but there didn't seem to be a lot of concensus around wanting this.

**Pull request closed without merging**
