### PR TITLE
I18n support for layout/application.html view

### PR DESCRIPTION
**Pull request by chaica**
I18n support for layout/application.html view

- app/views/layouts/application.html.erb : i18n support for layout/application.html view
- config/locales/en.yml : 18n english strings for layout/application.html
- config/locales/fr.yml : 18n french strings for layout/application.html

### CODE REVIEW

**Comment by chaica** [comment]
up about this PR for the i18n of lobste.rs :)

**Comment by chaica** [comment]
up about this PR for the start of the week ;)

**Comment by jcs** [comment]
@chaica what is the preferred way to handle pluralized words?  Is there something that makes the `pluralize` helper work automatically or does there have to be two entries in the locale file with the logic in the view to pick one or the other?

**Comment by chaica** [comment]
@jcs 

The official I18n Rails documentation gives [an explanation about pluralize](http://guides.rubyonrails.org/i18n.html#pluralization) and [the following howto](https://robots.thoughtbot.com/pluralizing-rails-i18n-translations) is quite straight-forward imho.

**Pull request merged**
